### ISSUE TITLE
Magicaxis removed from CRAN 

### ISSUE THREAD

**Issue by jjjermiah** [asgr/magicaxis#11]
[CRAN Page: MagicAxis](https://cran.r-project.org/web/packages/magicaxis/index.html)

hi developers,

I wanted to draw attention to this package being removed from the CRAN repository. 
As this package is a dependency for the [PharmacoGx](https://bioconductor.org/packages/release/bioc/html/PharmacoGx.html) package, its removal from CRAN results in the [failure of the PharmacoGx package to build on Bioconductor](https://bioconductor.org/checkResults/3.19/bioc-LATEST/PharmacoGx/). 

Is the maintenance of magicaxis on-going and can we expect the package to be back up on CRAN in the near future?

Thanks,
Jermiah

**Comment by akr777** [comment]
Same for ProFound :(

**Comment by asgr** [comment]
I just re-uploaded magicaxis to CRAN. There was a small issue when I did this back in November, and then I forgot to try again over Xmas.

**Comment by asgr** [comment]
This isn't the right place for any ProFound related issues, so I will close.

**Comment by jjjermiah** [comment]
What is the usual process for re-uploading to CRAN, will there be an update when it is re-instated as a package?

**Comment by asgr** [comment]
It is back on: https://cran.r-project.org/web/packages/magicaxis/index.html

I'm not sure exactly how bioconductor works, but it should be able to see it is back now/soon.

**Comment by jjjermiah** [comment]
thanks @asgr all builds are passing! Appreciate the prompt response.
