### ISSUE TITLE
Axis line thickness 

### ISSUE THREAD

**Issue by earlbellinger** [asgr/magicaxis#5]
Dear Aaron, 

Thanks for the nice package - I use it in all my figures! 

I am wondering if there is a way to change the axis line thickness with magicaxis. There is an unanswered stackoverflow question on this: 
https://stackoverflow.com/questions/52279490/specifying-axis-line-thickness-with-magicaxis

Do you have any tips? 

Thanks, 
Earl

**Comment by earlbellinger** [comment]
Ah - seems you've fixed it in the new version. Maybe you can push it to CRAN?

**Comment by earlbellinger** [comment]
Ah, but I see that lwd and lwd.ticks get rewritten throughout the method, taking from par()$lwd no matter what is specified. Personally, I would prefer to be able to supply lwd and lwd.ticks.

**Comment by asgr** [comment]
I think this is now fixed with the new lwd.axis and lwd.ticks options in v2.0.5. This won't be on CRAN for a while, but is here at least.
