### ISSUE TITLE
support for a pairs like function

### ISSUE THREAD

**Issue by Dailer** [asgr/magicaxis#9]
It would be nice to have a function similar to graphics::pairs having panel figures similar to those displayed by magplot. This type of figures would look more professional aesthetically and would be very useful (e.g. to display the results of Bayesian inference). Thanks.

**Comment by asgr** [comment]
I'm pretty sure you want to use 'magtri' for to make this plot? It's designed precisely for displaying MCMC chains.

**Comment by Dailer** [comment]
That was exactly what i was looking for, Aaron. My apologies for not being aware of this feature earlier. Thanks!

**Comment by Dailer** [comment]
Since you tagged this as an enhancement, I'd like to share some code I recently wrote, that you might be able to glean some ideas from. If you want, you can take a look [here](https://github.com/Dailer/Astro/blob/master/mcmc_cornerplots.R). It uses only the _magicaxis_, _ks_ and _sp_ libraries. An example of code output is shown below.
![cornerplot](https://user-images.githubusercontent.com/33109275/155902619-ad01787b-f07c-49f8-b12b-a8451370bcd0.png)
